name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build (macOS)
      run: swift build -v
    - name: Run tests
      run: swift test -v -Xswiftc -DWITHOUT_LIVE_SERVER
  
#  ubuntu-build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build (Ubuntu)
#      run: swift build -v
#    - name: Run tests
#      run: swift test -v -Xswiftc -DWITHOUT_LIVE_SERVER
